### ISSUE TITLE
Use gofmt and golint

### ISSUE THREAD

**Issue by Skarlso** [banzaicloud/pipeline#1003]
The go report of A+ is a lie. :)

One of Gos most approachable and best feature is a GLOBALLY standardized way of formatting the source code.

Not using that standard closes you off from people contributing who are using the global standard.

**Comment by sagikazarmark** [comment]
Can you please provide some examples where we do not follow the go standard. We use [GolangCI](http://golangci.com/) for linting, [gofmt and golint](https://github.com/banzaicloud/pipeline/blob/master/.golangci.yml#L15-L16) are explicitly turned on, so if there is any examples that must be a bug somewhere.

We totally want people to contribute to this project, so we are fully committed to fixing this issue. :)

**Comment by Skarlso** [comment]
Hey @sagikazarmark. 

Just open your A+ Go Report Card which tells you what issues you are having. :)

https://goreportcard.com/report/github.com/banzaicloud/pipeline

Also, normally the standard indentation is 4 spaces / tabs / bunnies / space stations. So seeing 2 is weird for me. But that's REALLLYYY stretching it. :)

**Comment by Skarlso** [comment]
For example, small things like these:

```go
/*
AuthApiService Delete an API token
Delete an API token
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param tokenId Token identification
*/
```

Go comments aren't Java comments. :)

**Comment by sagikazarmark** [comment]
@Skarlso my bad, I haven't actually opened Go Report Card. I'm not sure if you realized that, but the code under the `client` package is generated and excluded from our lint checks on purpose. Generated code is not for humans to read, although you kind of have to in order to use it, but you certainly don't need to modify it, so if this was keeping you from contributing to the project then I think you are safe from having to modify code that doesn't follow Go standards.

The rest of the warnings are also not really reliable on Go Report Card (for example go vet complains about an unknown format verb which can be used because of a custom implemented string formatter. With GolangCI we can safely ignore these "violations", but with Go Report Card we obviously can't.

As for the indentation size: honestly I also prefer tab size 4, I'm not exactly sure why we use size 2 tabs. But thanks to EditorConfig (which is also a standard tool these days) you don't have to pay attention, your IDE will take care of this and I don't think readability is much of an issue here.

I hope I addressed all of your concerns and nothing keeps you from sending a few PRs ;)

Feel free to close the issue if I did.
