### ISSUE TITLE
Cluster cannot be deleted if a node pool deletion fails

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/pipeline#3185]
**Describe the bug**
When a node pool is already partially deleted (ie. CF stack deleted), cluster deletion fails with the following (or similar) message:

```
XYZ is not authorized to perform: cloudformation:DeleteStack on resource: pipeline-eks-nodepool-CLUSTER_NAME/*
```

**Steps to reproduce the issue:**
1. Create an EKS cluster (with at least one, might try with two node pools)
2. Manually delete a node pool CF stack
3. Try to delete the cluster

**Expected behavior**
The cluster should be deleted.

**Additional context**
1. The customer who reported the issue has special IAM roles in place.
2. The node pool deletion logic is slightly more advanced in the node pool API (it skips already deleted resources). We should probably reuse that in the cluster delete flow.

**Comment by pregnor** [comment]
Blocked by #3223, #3224 

The solution is going to involve adding a check to the `NodePoolAPI.DeleteNodePool`'s stack deletion process preventing the system from trying to delete already deleted `CloudFormation` stacks - in this case node pools, because those cause access denied issues for permission-restricted Pipeline IAM users.

The two refactors referenced are required in order to 
1. properly separate the distribution specific implementation from the common (legacy) components.
2. provide a single implementation for the 3 locations executing the same action (deleting node pool).

This issue should cover the deletion logic extension with non-existing stack check only.

In the short run I'm going to extend the `eksproviderworkflow.DeleteStackActivity` with an optional stack ID input and a corresponding `cloudformation.DescribeStack` call (for available stack ID or falling back to available stack name) to ensure the stack is not being (already) deleted as I believe there is no use case where we wouldn't want to ensure we are only trying to delete existing stacks.
The reason behind optionality is that we use the same activity for other stacks as well, such as cluster, subnet, IAM and we do not currently have stack IDs available for those.

In the long run there is a plan to transition from stack name to stack ID usage with all CloudFormation entities, see #3225, #3226, #3227 for details, but currently we are aiming for the shortest solution as this is an existing bug in the system and those refactors are going to take significant amount of time (days).

**Comment by pregnor** [comment]
(forgot to add the resolve keyword to the corresponding PR)
